# Generated by Django 4.1.5 on 2023-01-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunnybook', '0012_remove_comment_dislike_remove_comment_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
